version: "3"

services:

  mongo:
    image: mongo:4.4.4-bionic
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/configdb:/data/configdb

  meilisearch:
    image: getmeili/meilisearch:v0.19.0
    ports:
      - 7700:7700
    volumes:
      - ./data/data.ms:/data.ms
