// GENDER
export const MALE = 'male';
export const FEMALE = 'female';
export const GENDER = [MALE, FEMALE];
export enum GENDER_ENUM_TYPE {
  MALE = 'male',
  FEMALE = 'female',
}

// USER ROLES
export const GUEST = 'guest';
export const BOT = 'bot';
export const USER = 'user';
export const ADMIN = 'admin';
export const SUPERADMIN = 'superadmin';
export const ROLES = [GUEST, BOT, USER, ADMIN, SUPERADMIN];
export enum ROLES_ENUM_TYPE {
  GUEST = 'guest',
  BOT = 'bot',
  USER = 'user',
  ADMIN = 'admin',
  SUPERADMIN = "superadmin"
}

// USER STATUS
// http://developers.socialcast.com/community-administrator-documentation/admin/managing-users/understanding-user-status/
// An active user can access the Socialcast community any time.
// A user becomes active as soon as the account set-up process is complete.
export const ACTIVE = 'active';
// A locked status prevents a user from logging in to the Socialcast
// community and can be used as a temporary measure –
// it must be unlocked by an Admin before the user can login again.
// An email notification will be sent to the user when his/her
// account has been locked/unlocked.
// The lock does not affect the content generated by the user
// and does not delete the account.
export const LOCKED = 'locked';
// A deactivated user cannot log in to the Socialcast community.
// Socialcast continues to maintain the user’s profile
// information and the community administrator can reactivate
// the user at any time.
// Only an administrator can deactivate a user.
// If a user deactivates his own account
// (through the Settings > Account Settings > Deactivate account link at
// the bottom of the page),
// Socialcast changes the user status to Pending Activation.
export const DEACTIVATED = 'deactivated';
export const PENDING_ACTIVATION = 'pending_activation';
export const STATUS = [ACTIVE, LOCKED, DEACTIVATED, PENDING_ACTIVATION];
export enum STATUS_ENUM_TYPE {
  ACTIVE = 'active',
  LOCKED = 'locked',
  DEACTIVATED = 'deactivated',
  PENDING_ACTIVATION = 'pending_activation'
}

// RBAC
export const PERMISSIONS = {
  users: ['create', 'update', 'find', 'get', 'remove'],
};

export const GRANTS = {
  [GUEST]: [],
  [BOT]: [],
  [USER]: ['update_users', 'find_users', 'get_users'],
  [ADMIN]: [USER, 'remove_users'],
  [SUPERADMIN]: [ADMIN],
};
